### ISSUE TITLE
Upgrade to latest kotlin version

### ISSUE THREAD

**Issue by etareduction** [exaV/screeps-kotlin-starter#16]
Currently, build.gradle.kts uses deprecated features and doesn't compile on the latest language version. It would be nice to update it and bump the kotlin version.

**Comment by etareduction** [comment]
I suppose we can just remove those lines
```kt
val processDceKotlinJs by tasks.getting(org.jetbrains.kotlin.gradle.dsl.KotlinJsDce::class)

// ...

dependsOn(processDceKotlinJs)
```
What they did seems to be just default behaviour now. At least i don't see any difference in the deployed bundle size when i remove it.

**Comment by exaV** [comment]
We just upgraded to kotlin-2.0.0-RC1
