### ISSUE TITLE
cant deploy on local server 127.0.0.1:21025

### ISSUE THREAD

**Issue by Krobys** [exaV/screeps-kotlin-starter#9]
cant deploy on local server

* What went wrong:
Execution failed for task ':deploy'.
> javax.net.ssl.SSLPeerUnverifiedException: peer not authenticated

can you help me, what i must to set as screepsUser and screepsPassword, if i try to deploy on the local server, what settings must be settled? if default user and password from official, the error showing.

**Comment by Tender2233** [comment]
@Krobys meet similar problem with you.
I can't even deploy on official server,cause by very similar problem.
Could I know if you successfully deploy your code to official server?

**Comment by exaV** [comment]
I have recently updated the 'deploy' task. Does it work now? If you get an SSL error you may need to set `screepsSkipSslVerify=true` in gradle.properties. However that is not necessary if you upload to the offical servers.

**Comment by Krobys** [comment]
if i use screepsSkipSslVerify=true
127.0.0.1:21027 there is no error, but deploying is infinite, on 92%
127.0.0.1:21025 the error is "javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake" (screepsmod-auth configured)
127.0.0.1:21026, the error is "javax.net.ssl.SSLException: Unsupported or unrecognized SSL message"

**Comment by Krobys** [comment]
After a lot of research, trying to send requests manually, it looks like the problem is that in gradle the connection is configured by https, but for https to work, a certificate is needed. At the same time, the connection with http works without a certificate, but gradle  is not configured for it.

On the official server all is works perfectly

**Comment by exaV** [comment]
this should work now with the new (java 11) http client
